name: workflow -> get stars

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'message to run'
        required: true
    

jobs:
  get_star:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13

    - name: Install dependencies
      run: pip3 install requests

    - name: Get stars
      run: |
        python3 get_star.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: update README.md
        committer_name: GitHub Actions
        committer_email: actions@github.com
